class names {
  static const ffNames = [
    'Death▄︻̷̿┻̿═━一',
    'ĐØĐ彡pHØeNîx',
    'ᴳᵒᵈ乡ᏒᏢ♕ᏦᎥᏞᏞᎬᏒ▄︻̷̿┻̿═━一',
    'Headhunter',
    '🅷🅸🆃🅻🅴🆁🅺🅸🅻🅻🅴🆁',
    'HuNg®¥ K¡LL€r',
    'Hydra. | dynamo',
    'Iήsͥⱥnͣeͫ',
    'J҉O҉K҉E҉R҉',
    'MVG•Ｎム丂ㄒㄚ',
    'SkULL༒CruSHeR',
    'SOUL々MORTAL',
    'ßãđßóÿ',
    'Ｓㄚ 么 乙 ツ',
    '𝕿𝖍𝖆𝖓𝖔𝖘’𝖘𝕮𝖍𝖎𝖑𝖉',
    '𝖙𝖍𝖊𝖉𝖆𝖗𝖐𝖝𝖍𝖔𝖗𝖓𝖊𝖙',
    'Xx-DΞΛDSH0T-xX',
    'ཧᜰ꙰ꦿ➢₦Ї₦ℑ₳ ༒',
    'ཧᜰ꙰ꦿ➢Iήsͥⱥnͣeͫ',
    'ཧᜰ꙰ꦿ➢ShozT',
    'ツTiger♰YourNameツ',
    'ツмαχαιя࿐',
    '乡GT乡 δΣΔδLΟζK',
    '亗『LEGEND』亗',
    '㊙H̶a̶c̶k̶e̶r̶一',
    'ǤƹȼӃσ ∞⃟',
    '─╤╦︻(◣_◢)︻╦╤─',
    'ǷƹϟҬƦθƴƹƦ',
    'Lΐᵍhtήΐήg',
    '◥Ӄɳɪʛɧʈ◤',
    'Hu͢͢͢Ň𝕥🅴ℝ',
    'Ǥąภgรteℝ',
    '乃丹刀D𝔯ac𝕦la',
    'ƤℜɆĐ₳₮Øℜ',
    '༺๖ۣۜ山ⱥή͢͢͢тed༻',
    'ɓʆαɕƘԹίηƘ',
    '★彡[βӀąçҟƑìɾҽ]彡★',
    '⇝尺σ¢ку',
    'ᙠossᴿᴬᴳᴱ',
    'BŁλ₡ƙCØBƦλ',
    '『Tʜóʀ』',
    '⋉𝓥amק͢͢͢i𝖗e⋊',
    '⌁Hⱥק͢͢͢קℽ⌁',
    'нα∂σω',
    '𒅒𝓥𝓮𝓷𝓸𝓶',
    'کƙɏɖเṽ℮Ʀ',
    'Ƙɨηǥ༒',
    '꧁Rąngeℝ꧂',
    '⧼∂ємση⧽',
    '༺Søk༻',
    '༺℘rส℘สtสŇ༻',
    'ᴏtσͷɢ乂',
    '༒ʂմղղվ༒',
    'ᴺᴸsᴇᴠᴇɴ°ᴵᴰ',
    '༒•B□Y•ℓєgєи∂༒',
    '༺Š₳₦Ü༻',
    '๖ۣۜⲦʀⲑⷱ͜ⲭⷮɪⲛ༻࿌',
    '☢️☢️☣️✝️NO°NAME✝️☣️☢️☢️',
    'X̺͆༒¢ɧąƙɛყι༒X̺͆',
    '꧁༒☬ℜ؏αᏞ_ᏦιηGs☬༒꧂',
    '꧁☆☬FRĘĘFÎRĘ☬☆꧂',
    '꧁☆•[ҎƦƟ]ҎȽɅȲȄƦ•☆꧂',
    '♛LegenNight♛',
    '༒B□Y•ℓєgєи∂༒',
    '⚡Tekⱥshi⚡',
    '▄︻̷̿┻̿═━一 ʜᴇᴀᴅsʜᴏᴛ',
    '†_РЯØ_R৷¢Ҝę_†',
    '༒eno°ᴴᴼᴿᴱ༒',
    '༺ᎦᏬᏋᏒ༒ᏋᏕ༻',
    '꧁H҉A҉C҉K҉E҉R҉꧂L🅴g🅴ήd',
    '『 SβC』',
    '༒¢ɧąƙɛყι༒™',
    '€¥ĹøbøMăł¥₩',
    '༒¢ɧąƙɛყι™༒',
    'Baby°Killer™',
    '♜fιяє♛㉺ℓєgєи∂',
    '◂HøűnĐş✰Øf✰jŲšȚïșě',
    '№•Т༟iс',
    '『ηç』►ƒϋιι●ut',
    '☠︎खूनी दरिंदा☠',
    'ᴬᵁᴿᴬ°᭄ᴍɪʟʟʏ࿐',
    '༄ᶦᶰᵈ᭄Aིkαຮh࿐',
    '۝O²κɪɴɢ࿐۝',
    'H҉A҉C҉K҉E҉R҉Lgήd',
    '༒۝♥ⓢⒶⒽⒾⓁ♥۝༒',
    'Sᴋ᭄Sᴀʙɪʀᴮᴼˢˢ',
    '༒•ĴØĶÉŘ•༒',
    '°༒AldyyExtece༒°',
    '༒ ★★ ༒',
    'ℓєgєи∂WۼℜۼWolŦ',
    'ᴳᵒᵈ•₦Ї₦ʝ₳',
    '༺KiLLeR༻',
    'Ŧﺂℜۼ ᴺᴬᵛᴵᴰᴬ͢͢Ɗ',
    'ˢᵁ•Sa̶ľľêH',
    'CREW❄️Ŧﺂℜۼ•❄️',
    'fℝⒶ₭¿ƬⱧ',
    '꧁༒ÅŞÄŠŞÏŅŞBŁĂČĶ༒꧂',
    '◥꧁དℭ℟Åℤ¥༒₭ÏḼḼ℥℟ཌ꧂◤',
    'ßãđßóÿ',
    'SOUL々MORTAL',
    'ĐØĐ彡pHØeNîx',
    'Hydra. | dynamo',
    '꧁༒ᶜʳᵃᶻʸBoy༒꧂',
    '╰ＨＳ╯ｃｒｉｍｉｎａｌ',
    'ᴮᵒˢˢ⚔●Lᵉᵍᵉᶰᵈ',
    'Badbøy',
    'ᏴᎡᎾᎢᎻᎬᎡˢᵟᵁᴬᴰ',
    'ＷＨＩＴＥ４４４',
    '✿ ᴍʀ ʟᴜᴄᴋʏ 亗 ✿',
    'BADGE ⁹⁹',
    'ᶫᵒᵛᵉ°᭄♡ᏴᎾY࿐°',
    'J҉O҉K҉E҉R҉',
    '亗『LEGEND』亗',
    'Ǥąภgรteℝ',
    '乃丹刀D𝔯ac𝕦la',
    '『Tʜóʀ』',
    '𒅒𝓥𝓮𝓷𝓸𝓶',
    'Ƙɨηǥ༒',
    '꧁Rąngeℝ꧂',
    '⧼∂ємση⧽',
    'HuNg®¥ K¡LL€r',
    'RAM 𝙵𝙵 ✓',
    'Black 444',
    'Pushpa',
    'VS. KING ❤️',
    'ⓥ RINKU FF',
    'Ⓥ ＣＲＩＭＩＮＡＬＦＦ亗',
    'BOBY 友',
    '༄●⃝☯Silent°᭄killer࿐',
    '𝙱 𝙰 𝙱 𝚄_𝚂 𝙷 𝙾 𝙽 𝙰',
    '𒆜Ꭺʟᴏɴᴇ♡ᴮᵒʸ࿐',
    'STAR•ＬＡＮＺ',
    'Single boy⁹⁹',
    '亗ᏦᎥᏞᏞᎬᏒᎬ★ᏴᎾYツ',
    '♛LegenNight♛',
    '꧁☆☬κɪɴɢ☬☆꧂',
    '★ᶦᶰᵈ᭄❂Gᴀᴍᴇʀ࿐',
    'ℓєgєи∂',
    'ƊᴏㅤσʀㅤƊɪᴇㅤ⓿❸',
    '亗 Ꭲ ɪ ᴛ ᴀ ɴ 亗',
    '☆꧁༒ ☬S.H.I.E.L.D ☬༒꧂☆',
    '⚡Tekⱥshi⚡',
    '꧁☤☞ᏚՓᏞᎠᏆᏋᏒ☜☤꧂',
    '♛N.O.O.B♛',
    'ΒαβγGΔΝG·ヅ',
    '×͜×ㅤ𝙰𝙻𝙾𝙽𝙴ㅤ𝙱𝙾𝚈 亗',
    '◤𝑺 𝑨 𝑻 𝒀 𝑨 𝑴 ◢',
    '╰‿╯ㅤϟＴＥＲＲＯＲ†',
    '☠︎खूनी दरिंदा☠',
    '༄ᶦᶰᵈ᭄Aིkαຮh࿐',
    '༺KiLLeR༻',
    'CREW❄️Ŧﺂℜۼ•❄️',
    'ᴺᴸsᴇᴠᴇɴ°ᴵᴰ',
    '꧁❀Ꮇ🅐Ꮋ🅐Ꮶ🅐Ꮮ❀࿐',
    '꧁༒ⓁⓊ☬ⒾⓈ༒꧂',
    '༒•B□Y•ℓєgєи∂༒',
    '乂°☆ƊΞvιⓁ☆°࿐',
    '★ᴋɪʟʟᴇʀ々दलाल ☯.',
    'Ꮮᴀғᴀɴɢᴀsᴀʟᴀ★',
    'ᴏᴘ ɢᴀᴍᴇʀ ʏᴛ',
    'ιмραятιαℓヅ',
    '亗Bꜱ Lᴇɢᴇɴᴅ !!',
    '░M░O░H░A░N░B░O░S░S░',
    '✿Ɱའ.ʀᴀʜᴜʟ★࿐',
    '☬乂J꙰O꙰K꙰E꙰R꙰乂☬',
    '˙·٠•●༒☬Pꜱʏᴄʜᴏ Kɪʟʟᴇʀ☬༒●•٠·˙',
    '❖Sʜᴏᴋᴀᴛ᭄ᴮᴼˢˢ',
    'तेरी मौत',
    '░K░U░N░A░L░',
    'Rᴅx𒆜ᴅʏɴᴀмo࿐',
    '✰ɢσdᬊ᭄Кιℓℓєя᭄',
    '╰ˣ⁴ˢ╮SKYL✿RD',
    'ᵀᵉᵃᵐ★ᎳᎪᏒᏒᎥᎾᏒ★',
    '꧁༒𝓓𝓪𝓷𝓲𝓼𝓱༒꧂',
    '★VꕯP_GoDʙᴏʏツ',
    '❦Sorry To Kill❦',
    'Vɪᴘᴇʀ巛Vᴇɪɴꜱ',
    '᭄ＲＯＭＥＯ➳',
    '꧁༺₦Ї₦ℑ₳༻꧂',
    '꧁༒•P£R£B∆Y∆•༒꧂',
    '๖ۣۜƊynสm๏❥',
    '『 VLT 』°β®Ü¥Π€',
    '✞ঔৣ۝Ðivâgar۝ঔৣ✞',
    'Tekⱥshi',
    '乂S H I K A R I乂',
    '꧁ᴵᴬᴹArmy_Man™꧂',
    '🅷🅸🆃🅻🅴🆁🅺🅸🅻🅻🅴🆁',
    'J҉O҉K҉E҉R҉',
    'Xx-DΞΛDSH0T-xX',
    'ཧᜰ꙰ꦿ➢ShozT',
    '★彡[ĐàŔk々Š0ūŁ]彡★',
    '『VOG』™•☬Ǥнσsτ࿐',
    '╰‿╯ｔｏｘｉｃｏᴳᵒᵈ',
    'ᵃᴷᶻ·L̶e̶a̶d̶e̶r̶',
    '★ᴾᴿᴼ❥Ӄᴎ͟͞ɪ͟͞ԍ͟͞ʜ͟͞ᴛ★',
    '❶ ❷ ❸ ❹ ❺ ❻ ❼ ❽ ❾',
    '─╤╦︻(◣_◢)︻╦╤─',
    '𒅒𝓥𝓮𝓷𝓸𝓶',
    '༒•B□Y•ℓєgєи∂༒',
    '━╤デ╦︻☬DETRØyER☆☬✰DEViL☬▄︻̷̿┻̿',
    '♜fιяє♛㉺ℓєgєи∂',
    '『᭄░K░U░S░H░A░N░』᭄',
    '《NOOB》',
    '๖ۣۜℜᎥᖙer',
    'Iήsͥⱥnͣeͫ 69',
    'ᏕᎷᎧᎧᏦᏋᏒ.ԿՁՕ™',
    '❖ᴀʀʏᴀɴ_ʏᴛ●࿐',
    'OƤ. 🅐︎ɴᴋɪᴛ☠︎︎✓',
    '✪︻┳═一ҜIŁŁ€ŘҜIŇG♚',
    '☠︎𝕯𝖊𝖒𝖔𝖓☠︎',
    '༄ᶦᶰᵈ᭄ⓀⒾⓈⓃⓄⓇ.࿐',
    'Vΐct𐍉ℝΐ𐍉us♛',
    '╰ˣ⁴ˢ╮SKYL✿RD',
    'Fɪɴᴀʟ々Sᴛʀɪᴋᴇ',
    'Death▄︻̷̿┻̿═━一',
    'S ᭄࿐ＴＡＩＬＯＲ࿐',
    '尺ムGE๛HITMAN',
    'Ir๏nͥMaͣnͫ⇝',
    'CREWŦﺂℜۼ•',
    '༒❦Sorry To Kill❦༒',
    '꧁ঔৣ☠︎ĐØŘ€ΜØŇ☠︎ঔৣ꧂™',
    'ঔৣ۝۝ঔৣ',
    '╰ ᵀᵘ ╯Ｃｏｍｐａｄｒｅ',
    'Speed.{Boy}',
    'мคкคłคdłค',
    'ＯＰ༉ＶＩＮＣＥＮＺＯ',
    'Vɪᴘᴇʀ巛Vᴇɪɴꜱ',
    'ᴠɪᴘ ɢᴀᴍɪɴɢ',
    '★꧁•Ƀ͢͢͢Ɇ₳Ŧ༒ß۝Ƴ•꧂★',
    '◌⑅⃝●♡⋆♡DRD♡⋆♡●⑅◌',
    '°°|︻╦̵̵͇GANGSTER︻╦̵̵͇̿̿̿̿╤─••',
    'G₄K『e n t i g a m e r』',
    '『ℜℓ』•彡NINJA彡',
    'гครtค',
    'ᴳᵒˡᵈȿ҉קเภtƺr',
    '༺Ꭶ₦ЇꝔ€ℜ༻',
    'ツﻬஐﻬ•ĂŤĚŇĂ•ﻬஐﻬツ',
    '᚛ᷝ ͣ ͫS℘สrtสŇ ͭ ͪ᚜ͤ',
    '๖ۣۣۜﷻ↭syko↭ﷻ๖ۣۣۜ',
    'ℜ؏αᏞ_ᏦιηGs',
    '༺ṅȏ༒ɢѧṃє༒ṅȏ༒ʟıғє༻',
    '༒ÅŞÄŠŞÏŅŞBŁĂČĶ༒',
    'sv̸iииaヅ',
    '༺Søk༻',
    '༺℘rส℘สtสŇ༻',
    'ᴏtσͷɢ乂',
    '༒ʂմղղվ༒',
    'ᴺᴸsᴇᴠᴇɴ°ᴵᴰ',
    '༒•B□Y•ℓєgєи∂༒',
    '༺Š₳₦Ü༻',
    '๖ۣۜⲦʀⲑⷱ͜ⲭⷮɪⲛ༻࿌',
    'NO°NAME',
    'X̺͆༒¢ɧąƙɛყι༒X̺͆',
    'ᏤᎪᏒᎶᎪᏚ',
    'Bæ',
    'Bama.Boy',
    '♛LegenNight♛',
    '༒B□Y•ℓєgєи∂༒',
    'Tekⱥshi',
    '▄︻̷̿┻̿═━一ʜᴇᴀᴅsʜᴏᴛ',
    '†_РЯØ_R৷¢Ҝę_†',
    '༒eno°ᴴᴼᴿᴱ༒',
    '༺ᎦᏬᏋᏒ༒ᏋᏕ༻',
    '͡°͜ʖ͡°)¯_(ツ)_/¯(ง͠°͟ل͜',
    '『SβC』',
    '༒¢ɧąƙɛყι༒™',
    '€¥ĹøbøMăł¥₩',
    '༒¢ɧąƙɛყι™༒',
    'Baby°Killer™',
    '♜fιяє♛㉺ℓєgєи∂',
    '◂HøűnĐş✰Øf✰jŲšȚïșě',
    '№•Т༟iс',
    '『ηç』►ƒϋιι●ut',
    '☠︎खूनीदरिंदा',
    'ᴬᵁᴿᴬ°᭄ᴍɪʟʟʏ࿐',
    '༄ᶦᶰᵈ᭄Aིkαຮh࿐',
    '۝O²κɪɴɢ࿐۝',
    'H҉A҉C҉K҉E҉R҉Lgήd',
    '༒۝♥ⓢⒶⒽⒾⓁ♥۝༒',
  ];
  static const pubgNames = [
    '꧁༒☬smony☬༒꧂',
    '꧁༺₦Ї₦ℑjj₳༻꧂',
    '꧁•TBlackSoul•ᴳᵒᵈ꧂',
    '꧁༒☬Bad☬*&Girl☬༒꧂',
    '꧁༒☬M̷O̷NN̷S̷T̷E̷R̷☬༒꧂',
    '꧁༒☬ROCKSTAR☬༒꧂',
    '꧁༒♛BADHSAHH ♛༒꧂',
    '꧁༒♛IAMTHEKING ♛༒꧂',
    '꧁️☠️ՇѧмѯNOTθѵэя☠️꧂',
    '꧁ঔৣBELEIVE☬✞✞☬ঔৣ꧂',
    '『GMWArrRdenLF',
    '『ツ』☆Ƭo×ᎥURWEREℂ',
    '•Who Am I•',
    '༒☬〖ℳℜKJND〗 ℜoͥᴍaͣnͫ73☬༒',
    '≪*********≫',
    '▄︻┻═┳一…..',
    '▄︻┻═┳•••••….',
    '◥꧁དℭ℟Åℤ¥༒***₭ÏḼḼ℥℟ཌ꧂◤',
    '◥꧁དDevilツIS Backཌ꧂◤',
    '◥꧁དALOJonEg-Taཌ꧂◤',
    '◥꧁ད{}[]β”α”d°₳{}s§ཌ꧂◤',
    '◥ᖫℭRRяαZZŸ༒₭ɨllǝ℞ᖭ◤',
    '☁✨爱Sηιρєrz爱✨☁',
    '★彡[ĐàŔk々Š0ūŁ]彡★',
    '★彡[DEADLY ᴋɪʟʟᴇʀ]彡★',
    '♛ᴿᴼᵞᴬᴸ꧁ĂĹĨganj꧂™',
    '⚔️BadAss⚔️',
    '๕ۣۜGODZΞUS™',
    'Agent_786',
    'IAM',
    'DEADŠTØŔM',
    'ĐàŔk[] {}Š0ūŁ',
    'ĐàŔk””TEMPER',
    '2222DEADPØØL222',
    'IamDeath▄︻̷̿┻̿═━一',
    'GØĐ彡pHØeNîx',
    'ᴳᵒᵈ乡ᏒᏢ♕ᏦᎥᏞᏞᎬᏒ▄︻̷̿┻̿═━一',
    'Hydraa. | ddynggamo',
    'IamIήsͥⱥnͣeͫ',
    'IamIήsͥⱥnͣeͫ°',
    'J””O””K”””E””R',
    'Iam•Ｎム丂ㄒㄚ',
    'Proud',
    'Head༒CruSHeR',
    'IamMortal',
    'SOUL々IMMMORTAL',
    'ßãđßóÿ2',
    'ＳSSㄚYYYYY 么 乙 ツ',
    'Iam',
    'DΞΛDSH0T2',
    'ཧᜰ꙰ꦿ➢₦iiЇ₦nnℑ₳ ༒',
    'ཧᜰ꙰ꦿ➢Iiήsͥsⱥanͣneͫe',
    'ཧᜰ꙰ꦿ➢ShorT',
    'ツLION♰YourNameツ',
    'ツмαχαUYUYιя࿐',
    '乡PT乡 δΣΔδLΟζK',
    '亗『IamLEGEND』亗',
    '㊙H̶a̶c̶k̶e̶pror̶',
    '༺J꙰”O꙰K”꙰”E꙰RR”꙰༻',
    '▄︻̷̿┻̿═━一',
    'wowM”Iⱥ”Khⱥℓifⱥ⚔',
    ' ∂αυ∂ibramahn',
    '༒☬Kong☬༒',
    '-.Ŧanahajiภøs',
    'I hate YÕÛ 33∅∅',
    '❖Sᴘyᴅʏ●FᎥre',
    '๖ۣۜIamƊynสm๏❥',
    ' ༒☬❤️IamHitman❤️☬༒',
    'དIam ༒ ₭ÏḼḼ℥℟ཌ',
    '《《☆Ģøđ øf deathř☆》》',
    '◥▓▓{}G:Ｈ:Ｏ:Ｓ:Ｔ▓▓◤',
    '༒☬IamRÎÐĘŘ ☬༒',
    '††╰⋆╮Rɪyugbᴢxᴛᴀʀʀ╰⋆╮††',
    'Baͥbuͣbͫhdjkchai',
    '︻╦̵̵͇̿̿̿̿★Ｉ ＡＭ ＴＩＮ ★︻╦̵̵͇̿̿',
    '░NOTG░A░R░I░B░',
    '༒•ĴØĶÉŘPro•༒',
    '฿ⱥtmafaⱥn',
    'ᵃᴷᶻ·L̶e̶a̶d̶e̶@r̶',
    'C•O•V•sjI•D¹⁹•ID♣',
    'Bคggΐʀคjsh',
    'ᶦᶰᎠᎬsᎥᵈ᭄✿mflkᏟhᎾᏒᎪ࿐',
    '))&B☢nd007',
    '꧁༺₦Ї2₦2ℑ2₳2༻꧂',
    '꧁༒Sa̶2d̶22B2∆22Y༒꧂',
    '❖ᴹᴿ°᭄✿ʀ2ᴏ2ᴍ2ᴇ2ᴏ࿐',
    '꧁ঔৣ☬✞L2ē2g2é2ñ2d✞☬ঔৣ꧂',
    '°ᴾᴿᴼ°к0ï0ʟ̸ʟ0є0я乡',
    '✞ঔৣ۝Ð0i00vâ0ga00r0۝ঔৣ✞',
    '☬๖ۣۜǤ0н0σs0τ༻',
    '◥࿐0ҽѵ00í0l༆ˡᵒʳᵈʙ0ᴀ0ʜ0ᴀ࿐◤',
    '꧁千0尺乇0乇千0丨尺0乇?꧂',
    'ĐǺ℟₭ ΆŃǤỀĽBe carefulØ࿐',
    'Iamℓєgєи∂',
    '༒Ǥ3₳3₦3ǤֆƬᏋЯ3༒',
    '༺Ꭶ₦3Ї3Ꝕ€3ℜ3༻',
    'Sΐ3ʟ3eŇτ3Kΐʟ3le',
    'Ꭰ3Ø3ή♛',
    'βa∂33ßo3y',
    'Captΐaή5ja5ck5spa5ℝ5rØw',
    'I0r00๏0nͥ0Maͣ0nͫ⇝5',
    '★☆•ⲘȺℂ•☆★',
    'boℽ',
    '⁣���Geղeral���͢͢͢lemen',
    '░B░O░S░S░ iamkaran',
    '۝₦ØØ฿۝',
    '༒❦DontKill❦༒',
    '❶ ❷ ❺ ❻ ❼ ❽ ❾',
    '༒☬ⓈⓊⓇⒺⓈⒽismyname ☬༒',
    'Juรτiήside',
    '乂I am S H I K A R I乂',
    '༒☬I amM̷O̷N̷S̷T̷E̷R̷☬༒',
    '❅I amPU๖ۣۜßGorreallyplaψer❅',
    'Riͣdͫer',
    's ᴘsʏᴄʜᴏ ✰',
    'Ṩlaรheℝer',
    '꧁༒Ǥ₳₦Ǥֆia,ƬᏋЯ༒꧂',
    '꧁ᴳᵒᵈ•iam₦Ї₦ʝ₳꧂',
    '꧁༺۝༒♛iamsђΐvน♛༒۝༻꧂',
    '꧁༒☬ypouraeŠCØŔPĨØŊ☬༒꧂',
    '༄ᶦᶰᵈ᭄ ▄︻┻═┳一ąkch',
    '꧁༒•P£R£B∆kjvY∆•༒꧂',
    '☢️☢️☣️✝️NO°NfvoAME✝️☣️☢️☢️',
    '꧁࿇ÐɑʀҟƑîEʀɛ;fi࿇꧂',
    '▄︻┻═┳一☬ Kkvfîřăñ ☬',
    '༒ᴳᵒᵈɢѧṃlfEklє®༒☬¥ï§µ§☬༒',
    '꧁༒☬:”::☬༒꧂',
    '༺Ꭶ₦ЇꝔE€ℜ༻',
    '๖ۣۜƊynสm๏❥',
    'SightsEets',
    'JoђEn๖ۣۜ山icҜ',
    '͢͢͢Y',
    '°”ן๏ђEภฬเςк”°',
    'Ni͢͢͢ήα',
    'IAM',
    'NinjaDulhan',
    '꧁༺IAm₦Ї₦ℑ₳༻꧂',
    'Ƥro3',
    'PeaseIce',
    '❅ᖘlayer3❅',
    '⌁FℝeefᎥℝepro⌁',
    'fͥreͣeͫfijkdjdre456',
    '0000000ᴸᴵᶠᴱ',
    '✰123Trixie123✰',
    '░Tΐxΐe123',
    'of꧂',
    'Søuljofthe฿oy',
    'Ṩ͢͢͢oบˡjaoftheᙠoy',
    'S͢͢͢ouloftheʝaᙠoψ',
    'Søuloftheα๖ۣۜßøy▤',
    '❅00Agen†786❅',
    '⪻Agnt786⪼',
    'FreefᎥrekiller',
    'serialк͢͢͢Ꭵller',
    '0τ0ђe͢͢͢0la0zℽb0oℽ',
    'e0ร0p0α͢͢͢0¢0i0',
    '「4444ℭ4444」',
    '00',
    '★彡[Mสˢ3†e3ʀc3i3ef]1彡★',
    'M1aͥ1stͣ1eͫ1rch1i1ef❥',
    '▄︻デM̷a̷y̷Yu̷r̷══━一',
    '★彡[ᴍᴀʏYᴜʀ]彡★',
    '꧁༒☬Y☬༒꧂',
    '꧁༺ʍǟʏYʊʀ༻꧂',
    '꧁꧂',
    '▀▄▀▄▀▄▀▄▀▄▀▄',
    '█▓▒­░⡷⠂MДУYЦЯ⠐⢾░▒▓█',
    'ⓐⓨⓤuⓡ',
    'ᗰᗩƳyᑌᖇ',
    'Ｍａｙyｕｒ',
    'ɹnʎyɐW',
    'ɯɐʎynɹ',
    'ɿuʏyɒM',
    '░M░a░yy░u░r░',
    '[M̲̅][a̲̅][y̲̅y][u̲̅][r̲̅]',
    '▄︻デS̷uom̷i̷t̷══━一',
    '★彡[ꜱᴜᴍmɪᴛ]彡★',
    '꧁༒☬m☬༒꧂',
    '꧁༺ֆʊʍmɨȶ༻꧂',
    '꧁m꧂',
    '▀▄▀▄▀▄m▀▄▀▄▀▄',
    '▄︻デaA̷h̷a̷m̷══━一',
    '★彡[ᴀʜaᴀᴍ]彡★',
    '꧁༒☬a☬༒꧂',
    '꧁༺ǟɦǟaʍ༻꧂',
    '꧁꧂',
    '▀▄▀▄▀▄a▀▄▀▄▀▄',
    '₦Ї₦ℑ₳',
    'Headhunter',
    '▄︻┻═┳一',
    '༒☬Bad☬Boy☬༒',
    '≪🆂🆄🆁🆅🅸🆅🅾🆁≫',
    'J҉O҉K҉E҉R҉',
    'Shroud',
    'BŁΛCKŠTØŔM',
    '𝖙𝖍𝖊𝖉𝖆𝖗𝖐𝖝𝖍𝖔𝖗𝖓𝖊𝖙',
    'Hydra. | dynamo',
    'SOUL々MORTAL',
    '༒☬sunny☬༒',
    '🅷🅸🆃🅻🅴🆁🅺🅸🅻🅻🅴🆁',
    '★彡[ᴅᴇᴀᴅ ᴋɪʟʟᴇʀ]彡★',
    'ĐàŔkツCÀMPER',
    'ĐàŔk Š0ūŁ',
    '◥ᖫℭяα𝕫Ÿ༒₭ɨllǝ℞ᖭ◤',
    '༺ṨήiͥpeͣrͫJⱥmes☘༻ ✨︻デ═一',
    '️☠️Շѧмѯ_️θѵэя☠️',
    '⚔️BadAss⚔️',
    'B O S S',
    'ঔৣ☬✞𝓓𝖔𝖓✞☬ঔৣ',
    '🐲Vΐ℘er',
    '•Who Am I•',
    'SΞΝSΛ1D',
    '🆁🅰🅽🅳🅷🅰🆆🅰',
    '✧D@RK✧⎠⎠乡✧BL@DE✧⎠⎠',
    '𝕿𝖍𝖆𝖓𝖔𝖘’𝖘𝕮𝖍𝖎𝖑𝖉',
    '☁✨爱Sηιρєz爱✨☁',
    'Aʛɘŋt47',
    'Mɩʛʜtƴ Mʌʆɩʌ',
    'Kɩŋʛsɭʌƴɘʀ',
    'Cʜɩcĸɘŋɭovɘʀ',
    'Dʌʀĸ Pʀɩŋcɘ',
    'Fʌʋɭtƴ Dɘvɩɭs',
    'Coɱpɭɘx Sɭʌƴɘʀs',
    'ʀɩppɘʀ',
    'TʀɩŋɩtƴWʌʀʀɩoʀ',
    'Pɭʌɩŋ Pʀɩvɩɭɘʛɘ',
    'Zɘʌɭoʋs Sqʋʌɗ',
    'Oʋtʀʌʛɘoʋs Doɱɩŋʌŋcɘ',
    'ɗʌʀɘɗɘvɩɭ',
    'Dɘstʋctɩvɘvɩʀʋs',
    'Fʌŋʌtɩcʌɭ Tƴʀʌŋŋƴ',
    'Gɭɩstɘŋɩŋʛ Pʀɘstɩʛɘ',
    'Kɩɭɭsʜot',
    'Cɭoʋɗƴ Pɘʀpɘtʀʌtoʀ',
    'Hʋŋʛʀƴ Aɗɱɩʀʌɭs',
    'Tonight Gamer',
    'Green Ghost',
    'PUBG Lover',
    'Inimical Thugs',
    'Guncap Slingbad',
    'Straight Gangsters',
    'Complex Slayers',
    'Eat Bullets',
    'Bloss Flop',
    'Highlander Monk',
    'Mortified Coercion',
    'Dead Deal',
    'Knuckle Duster',
    'Fighting Machine',
    'Faulty Devils',
    'Collateral Damage',
    'Tango Boss',
    'Left Divide',
    'Overkill',
    'Keen Team Six',
    'Odd Hooligans',
    'Married Man',
    'Alpha Returns',
    'Shoot 2 Kill',
    'Kill Spree',
    'Jack The Ripper',
    'Outrageous Dominance',
    'Agent Hercules',
    'Lowercase Guy',
    'Happy Killing',
    'Junkyard Dog',
    'Veteran of Death',
    'PUBJESUS',
    'Brute Fact',
    'Optimal Aces',
    'Fear Butchers',
    'Hog Butcher',
    'Fuzzy Pack',
    'Brash Thugs',
    'Night Magnet',
    'Bad soldier',
    'Dead Shot',
    'Chicken Lover',
    'Mortified Coercion',
    'Organic Punks',
    'LocalGrimReaper',
    'PUBGian',
    'Dancing Madman',
    'Pro Headshot',
    'Annoyed Power',
    'Hungry Admirals',
    'Captain Jack Sparrow',
    'Quarrelsome Strategy',
    'Headshooter',
    'Cloudy Perpetrator',
    'Strange Love',
    'Cloudy Perpetrator',
    'Pixie Soldier',
    'Left Divide',
    'Keen Team Six'
  ];

  static const cocNames = [
    'Ideal Lightning',
    'King Zurich army',
    'Watts warriors',
    'Brahmasmi soldiers',
    'Dharma Gurus',
    'Commando2',
    'AmIKilling',
    'Kill Steal No Deal',
    'Real Chill',
    'Demon Kong',
    'Gods of Undead',
    'God of Blood hunters',
    'Gutsy Studs',
    'Frenzy Shooters',
    'Covert Destroyer',
    'Tilted Stabbers',
    'Vampiric Ghosts',
    'Dark Spirits',
    'C-19 Parasites',
    'Frantic Saboteur',
    'Dirty Grenadier',
    'Electric Tank',
    'Grim Noob',
    'Noobies Choosies',
    'Loser Hunters',
    'King-Pins',
    'Gun Lords',
    'Snipe the Hype',
    'Loose Characters',
    'Headshooter',
    'AWMLover',
    'AK47',
    'Agent47',
    'Pubgstriker',
    'Gangs of COD',
    'Demons and giants',
    'Championofseas',
    'Quarrelsome Strategy',
    'Hungry Admirals',
    'Cloudy Perpetrator',
    'Fuzzy Pack',
    'Straight Gangsters',
    'Mortified Coercion',
    'Lyrical Armed Services',
    '20+ CoC Clan names for girls',
    'YourBFStares',
    'Shy Gun',
    'Candy Queens',
    'Rosies',
    'Killing Kissers',
    'Margolem',
    'Bloody Mary',
    'legendary Princess',
    'Slaying Girling',
    'Pink Leader',
    'Cinderella',
    'Padmavati',
    'Gun Digger',
    'Her Majesty',
    'Leading Light',
    'Queen Bee',
    'Battle Mistress',
    'Young Lady',
    'Winner Woman',
    'Chicky Fighter',
    'Gentle Woman',
    'Cute Crashers',
    'BeachesGotU',
    '40 Good Clan Names for CoC lovers',
    'Kiss No Bliss',
    'wizard harry',
    'Headhunter',
    'DEADPOOL',
    'Agent_Sergent',
    'Agent its urgent',
    'Thunderbeast',
    'Sniper',
    'DEATH MACHINE',
    'MADMAX',
    'Dead show',
    'GunSly Bruce Lee',
    'Bad soldier',
    'Psycho killer',
    'Gun Guru GG',
    'Sanskari',
    'Faadu',
    'JaiML',
    'Tomato',
    'Dihaati on fire',
    'Bihari Boy',
    'Katega',
    'Saras Player',
    'Straight Gangsters',
    'Mortified Coercion',
    'Lyrical Armed Services',
    'Outrageous Dominance',
    'Homely Sharpshooters',
    'Plain Privilege',
    'Brash Thugs',
    'Annoyed Power',
    'Demonic Criminals',
    'NashediGang',
    'Mighty Mafia',
    'Trollers goals',
    'KrkFans',
    'DuBose',
    'Complex Slayers',
    'Greasy Desperado',
    'Organic Punks',
    'Quarrelsome Strategy',
    'Mahismati',
    '50 Unique CoC Clan Names',
    'DJ Jije',
    'Dizzy Irresistible',
    'Nutty Domination',
    'Observant Force',
    'Selfish Soldiers',
    'Fanatical Tyranny',
    'Grieving Butchers',
    'Long-term Occupation',
    'Plain Privilege',
    'Disagreeable Liquidators',
    'Stupendous Knights',
    'Regular Discipline',
    'Abnormal Vigor',
    'Guttural Gangsters',
    'Zealous Squad',
    'Homely Sharpshooters',
    'Odd Hooligans',
    'Ruddy Exterminators',
    'Known Warfare',
    'Purring Coercion',
    'Annoyed Power',
    'Wretched Veterans',
    'Calm Outlaws',
    'Medical Rebels',
    'Faulty Devils',
    'Glistening Prestige',
    'Hungry Admirals',
    'Championof7seas',
    'Insaneshooter',
    'Deadshot',
    'Agent47',
    'Chicken lovers',
    'Pubgstriker',
    'Destuctivevirus',
    'Evildead',
    'Pubgaddictiv',
    'Gangsterpubg',
    'Hacker',
    'Pro-Grow Blow',
    'Ironman/some other hero',
    'Death gun',
    'Terminator x',
    'Thunderbeast',
    'Dynos',
    'Troll',
    'Dark Warrior',
    'Assassin 007',
    'Maarenge Marenge',
    'Brookie',
    'Popeyes',
    'Outrageous Dominance',
    'Homely Sharpshooters',
    'Plain Privilege',
    'Brash Thugs',
    'Annoyed Power',
    'Demonic Criminals',
    'Abnormal Vigor',
    'Optimal Aces',
    'Inimical Thugs',
    'Fear Butchers',
    'Left Divide',
    'Psychedelic Servicemen',
    'Militaristic Fighting Machine',
    'Ball Blaster',
    'Legends Reload',
    'Brute Fact',
    'Bloss flop',
    'Tango Boss',
    'Optimal Aces',
    'Inimical Thugs',
    'Fear Butchers',
    'Left Divide',
    'Psychedelic Servicemen',
    'Militaristic Fighting Machine',
    'Keen Team Six',
    'Fuzzy Pack',
    'Straight Gangsters',
    'Mortified Coercion',
    'Lyrical Armed Services',
    'Outrageous Dominance',
    'Homely Sharpshooters',
    'Plain Privilege',
    'Brash Thugs',
    'Nutty Domination',
    'Complex Slayers',
    'Faulty Devils',
    'Fanatical Tyranny',
    'Odd Hooligans',
    'Organic Punks',
    'Quarrelsome Strategy',
    'Hungry Admirals',
    'Cloudy Perpetrator',
    'Militaristic Fighting Machine',
    'Keen Team Six',
    'Holy JESUS',
    'Lone_Ranger',
    'Dark Warrior',
    'XxGoldenWariorxX',
    'iEnVy UraniumPotato',
    'Super Squad',
    'Tronners Concord',
    'Kirkpatrick',
    'Sudden Death',
    'Maori',
    'Turnbull',
    'SuRE ChroMe',
    'Mar Byres',
    'Leask',
    'ReC',
    'Insomnia Swordplay Velocity',
    'Patullo',
    'RiseOfAbyss',
    'Martial Warlocks',
    'Wolverines Blood',
    'RaG3',
    'Clan Doom Hammer',
    'Cathcart',
    'Myst Heart Vs Feather',
    'Twoearth',
    'Tears of Gaia',
    'Written in Blood',
    'iLLuZioNz Clan or Clam?',
    'NoNerds',
    'DreTron',
    'Whitefoord',
    'Melville',
    'Fenton',
    'Crawford',
    'The Oracle',
    'Tronners Unlimited',
    'Legendarya',
    'Lust Arrow-Clan',
    'S.Y.G. (Stole Your Glory)',
    'Detonate Farm4us',
    'Vans Pennycook',
    'Lennox SaS',
    'Ross Forsake the Fallen',
    'Ramsay',
    'Untitled',
    'Wallace',
    'Apocalypse',
    'Buchan',
    'Moffat Nova',
    'Dispatch',
    'Avl Clan',
    'The Immortal 50',
    'RioT',
    'Zombie Hordes',
    'Gaia',
    'Butchers',
    'Void',
    'Green',
    'Primrose Cannibals Halkerston',
    'Weir',
    'Thedarkwim',
    'Destroy The Noobs',
    'Bobin Mercer',
    'Uprising',
    'Phoenix Viking',
    'Epicenter Glas',
    'Spongerz',
    'Osiris’ Scale',
    'Dominate',
    'Regicide Menzies',
    'Clan or Fam',
    'Lost Legion',
    'Forrester',
    'aMaZeee Lumencidium',
    'CoC Boss',
    'Redemption',
    'Philistines Anatomy of Death',
    'ClashForCash',
    'Zombie',
    'DeLiiRiuM Kinloch',
    'JustGeeks',
    'Skirving Bitten Bone Bits',
    'Scrymgeour',
    'Murder For Hire',
    'green Zone',
    'Spalding Clan of Coats Swarm',
    'Heresy',
    'ifarm.01',
    'Hitmen',
    'Rait',
    'Nevoy',
    'Death Dealers',
    'Xtreme',
    'Salt of the Fields',
    'Anderson Cubed2',
    'Weedie',
    'Pantheon',
    'Sedition Muirhea',
    'Nesbitt Cranstoun',
    'Power Within',
    'Predation Black Magic',
    'Babos',
    'DeViiLz Tank DONATORS',
    'Volume Zero',
    'Anstruther',
    'Hangmen',
    'Maxton',
    'DeMartino Under_eS!:timated',
    'eeZ, Tat',
    'Boswell Alpha',
    'Falconer',
    'Newlands',
    'Natural Born',
    'Tribes',
    'DATING CLAN',
    'Jackals',
    'Greek Fire',
    'Farmer',
    'Monteith',
    'Rutherford',
    'Glendinning',
    'Tennant',
    'Magister Mortalis (masters of death)',
    'Survival Strategy',
    'Kung Fu Phooey',
    'Hippocratic',
    'Hannay Knaves',
    'Norvel',
    'Projectiles',
    'CoD',
    'Russell',
    'Horsburgh Swift',
    'Clan Axis',
    'Broun',
    'solar Immortals',
    'Rebels Blair',
    'Shields',
    'Performance MiSTaKeZ',
    'Sliice Slay and Flay',
    'Bloodline',
    'Hope',
    'FORUM ELITE',
    'CraZe',
    'Tronners Clan',
    'story unfolds',
    'Vultures',
    'Urquhart',
    'CoD',
    'Noobs',
    'Embers Rising',
    'Gregor',
    'Team',
  ];
  static const codNames = [
    '尺ΛЛƓƐ尺',
    'ѕтσям',
    '𝐁𝐫𝐮𝐢𝐬𝐞',
    'Mσσɳɾιʂҽ',
    'ŘΔĐƗĆΔŁŞ',
    '𝔹𝕆𝕋',
    'αℓρнα мαкє',
    '﹄Gคղgຮte͢͢͢尺﹃',
    'Ａｎｇｒｙ Ｗｏｌｆ',
    '𝓓𝓮𝓶𝓸𝓷 𝓗𝓾𝓷𝓽𝓮𝓻',
    'ℙ𝕒𝕟𝕕𝕒',
    'Wrê¢kågê',
    'ჯէɾҽʍҽ φӀąվҽɾ',
    '𝕭𝖗𝖚𝖎𝖘𝖊𝖗',
    '𝓑𝓸𝓽𝓴𝓲𝓵𝓵𝓮𝓻',
    '乃ӨƬΉЦПƬΣЯ',
    'D҉e҉adH҉un҉t҉er',
    '🅷🅴🅰🅳🅷🆄🅽🆃🅴🆁',
    'Difficult Sharpshooters',
    'GΉӨƧƬiΣ',
    'لօʂհ',
    '✭кιℓℓєяQυєєη',
    '山αяℓσ¢к♦️',
    '━╤デ╦︻S༒N༒I༒P༒E༒R',
    '𝓢𝓹𝓾𝓷𝓴𝔂',
    'Яe̷s̷u̷r̷r̷e̷c̷t̷',
    'Oᛗ𐌄ĞᎯ꧅',
    'CℝØne꧂',
    '𐄡M☢uήtสiή𐄪',
    'няσмιυм',
    '꙰ꦿ➢❦︻╦̵̵͇╤─Θ',
    'Human Shield Carnegie Armored Army',
    'Ӄᴎ͟͞ɪ͟͞ԍ͟͞ʜ͟͞ᴛ',
    'קմήk',
    'A Martyr’s Death',
    '𝓓aeήeryʂ',
    'Stoℝᴍboℝภ⚐',
    '𝕰nigm@',
    'WᎥήήΣr',
    '𝒞สภ∂y',
    'Paterson Moubray Medieval Methods',
    'M𝖊†aℓ',
    'SｋULL#10 ω⊙↳Ϝ',
    '𝐌𝐚𝐱𝐢𝐦𝐮𝐬',
    'ℌ𝔢𝔞𝔡𝔰𝔥𝔬𝔱',
    'XÆA',
    'R̷e̷s̷u̷r̷r̷e̷c̷t̷',
    'DEViL☬▄︻̷̿┻̿',
    'av͢͢͢iØบr',
    'Яe͢͢͢gℝet',
    'SeŇøri𝕥α⇝',
    '山øℓf',
    '𝕿yrⱥnny',
    'Bʀʌv☼',
    'CoD bot.',
    'LivᴇlץLⱥ∂',
    '尺丨丂乇',
    'DΣƧƬIПY',
    'King of the Dead.',
    'LoN3',
    'Dilwale Tu Silwale',
    'Calm-e-killings',
    'Detonator',
    'υηκηοωηAnnihilator',
    '𝓢𝓹𝓾𝓷𝓴𝔂',
    'Sภΐ𝓹eℝ',
    'Intrøvert',
    'Night🅼αrǝ',
    '𝕿yrⱥnny',
    'ĐàRkÇlöwn',
    'Rสve🅽𓆪',
    'SimpӀ𝔂𝕿he𐐚eรt',
    'yϻթђᵒny',
    'K͢͢͢ᎥℓℓVeภ†',
    'Mαniสc',
    '山αяℓσ¢к♦',
    'HyPer',
    'Hunt3r',
    'Critical',
    'Troll',
    'R3kt',
    'Bʀʌvo',
    'SｋULL#10 ω⊙↳Ϝ',
    'Ne Agito Oppeto (death is unavoidable)',
    'Zue.',
    'Sɭʌʋʛʜtɘʀ ĸɩŋʛ',
    '★ Escape.',
    'Hollowman',
    '➻❥β¡η﹏✍',
    'SOUL々MORTAL',
    '➻❥︵Čĥiέň ☆ Dong ☆ Tower ☆',
    'ª№•乇яŁმИցցﾑ≝',
    '༒',
    'Wrecker',
    '✥Ϝѻϰ⋆',
    '➻❥︵Aɳɧ﹏❣',
    '✵ℳïɛ‿❁',
    'Jerry ☆',
    'Gunner',
    'ɓʌɗɱʌsʜ',
    '➻❥ℛȇɳ ༉ ➅➈',
    'Ronin',
    'ℑi ռ ➻❥︵ℬăɳg * .:',
    'ツﻬஐﻬ •ĂŤĚŇĂ• ﻬஐﻬツ',
    '乂✰ɢuçí °ɢαͷɢ✰乂',
    'Sniper',
    'Peace‿✶ ♡',
    'Scream',
    '『ZΞ℞Ø』么 Sonu',
    '♈nolo♈',
    'Agent47',
    'Roadkill',
    '༺༒₦Ї₦ℑ₳༒༻',
    'Mirth',
    '‿✰Cђangε',
    '♚¬Mʏℒ Օ vɛ',
    'ɦTips ☆☆☆☆☆',
    'Menace',
    'EK Ladki',
    'Blood',
    'Bastian',
    '☬sultan☬',
    'Goku',
    'Deadly',
    '# 24 # _Any_ # 6 #',
    'Chasm',
    'Thoth',
    'Spock',
    'Fist',
    '➺❥VH❥➺',
    'Minh ☆ Candy',
    '♔⌒βοοrjη # 2',
    'VɘʛʌŋMɘʌt',
    '✿ČàTɧối❼❷',
    'B O Fi',
    'Altair',
    'ᶛᵒ᭄➢Vᴿ',
    'ℓєgєи∂WۼℜۼWolŦ',
    'Dizzy',
    'ᵃᴷᶻ°ΒαβγBæツ',
    'Page ➻❥',
    'Extʀʌtɘʀʀɘstʀɩʌɭ Dʀƴʌɗ',
    'Ash',
    'Cyrax',
    '❄Rius♒',
    'Khan',
    '࿇ ͥ ͣ ͫᏕʜɪᴇ༒Ɗσ؏Ḽ•ᴵᴰ࿇',
    'Walking Pegasus',
    'Logan',
    '➻❥๖R❂Sɛ﹏❣',
    'あ た く ✽Haru',
    'Bowser',
    '❥︵ ₷ ilεn է …',
    'SOUL | Mr.Akram',
    'Zero',
    '♔Muyn︵ ღ',
    'Nlyk Lðk',
    'ßaɗsʜàʜ',
    'Killer',
    'Menace',
    '✟ ₪ i',
    '___ Fairyy___',
    '☠ми⁰⁰⋆',
    'ℳǐʊ³⁴ ♜',
    'Sʌŋsĸʌʀɩ',
    'Sʊ 廴 ɪ︵❣',
    'ʙᴘᴄ•_༒ᶜᴿᴬᶻᵞkíllє®™༒©',
    '須DⴽΛGΘΠ•須',
    '乂ᴵ ᴬᴹ Ƥʸʳᵒ†̶ᵉ̶ᶜ̶ʰ 乂',
    'Love to Win',
    'MʌʀɩoIsBɘttɘʀ',
    '╰☜Tool☞╯',
    '➻❥✿ℳυɳ',
    '✵G-Ɗragøn',
    'Ironclad',
    'Vapor',
    '# D @ vid',
    'I’AM☞Zin',
    'Dracon',
    '༺ṅȏ༒ɢѧṃє༒ṅȏ༒ʟıғє༻',
    '༺Leͥgeͣnͫd༻ᴳᵒᵈ',
    'Deadly',
    '❂Jun',
    'Dementor',
    'Wanted',
    '♪ Yoko',
    'Balrog',
    '♡♡ {needle} ♡♡',
    '♥ ◇ e & amp; a ◇ ♥',
    '༄۵Ḅ',
    'Uproar',
    'Freak',
    '♔Âητỷ',
    '➻❥ß❍❍﹏❣',
    'Matrix',
    '➻❥๖ ۣۜ ƒø✘',
    'kidnhi ',
    'Geronimo',
    'ᴳᵒᵈ᭄ꫝཞꪖꫝꪏ࿐',
    'Wardon',
    '❣ 廴 σҩɛ ❣﹏C ° Á ° O﹏❣',
    'Nama kecil di atas kaya mozila',
    'Shady',
    'ßãđßóÿ',
    'Kraken',
    'Ãttaçķeř_ßwîķriť',
  ];
}
