name: easy_nickname
description: This package give you support to add your custom nicknames. Your can also use default nicknames as well.
version: 1.0.2
homepage: https://github.com/nooralibutt/easy_nickname
repository: https://github.com/nooralibutt/easy_nickname

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: